"""
自动从 Java 代码迁移生成
Generated by Java to Python Migration Tool
"""

class Calculator:
    """Java 类 Calculator 的 Python 实现"""

    _PI: float = 3.14159

    def add(self, a: int, b: int) -> int:
        return a + b

    @staticmethod
    def circle_area(radius: float) -> float:
        return Calculator._PI * radius * radius

if __name__ == "__main__":
    # TODO: 添加主程序入口
    pass
